services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - tareas-net

  app:
    build: .
    container_name: microservicio-tareas
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - tareas-net

volumes:
  mongodb_data:

networks:
  tareas-net:
